R/ecoretriever.R

The `datasets` function currently has some behavior that makes it hard to work with from within R.
` length(datasets()) # returns 1`
`class(datasets()) # returns "integer"`
I made a small change that captures the output from `retriever ls` and makes it available to R instead of printing it.

intern results from retriever ls

---

R/ecoretriever.R

I detected that the function `get_updates` was producing errors because 1) a last minute change to the argument definition of this function was not properly implemented, and 2) sometimes the retriever does not download new scripts and thus returns a log without any text. These two commits solve these two problems. If no scripts are downloaded this is simply relayed to the user.

Patch the get_updates function

---

R/ecoretriever.R

An extra copy of the `dataset` argument had crept into the sub_dir clause
of the download function. This result in errors if the sub_dir option is
used.

Fix --subdir download by removing extra argument

---

DESCRIPTION
NEWS.md
R/ecoretriever.R

system() works for calling the retriever's CLI on some Windows systems
but not others. This change checks the operating system and uses shell()
if the R package is running on Windows.
Fixes #32.

Use shell() on Windows systems

---

R/ecoretriever.R

Fixes #70 by adding the default anaconda/miniconda install directories to the search path.
Tested on Ubuntu and Windows 10.
Replaces #79 (since I mucked up the history).

Search for anaconda installs of retriever

---

DESCRIPTION

As suggested by Dan McGlinn (and I agree), Shawn's contribution of solving
the Anaconda problem merits being added as an author.

Adding Shawn Taylor as an author

---

R/ecoretriever.R

The soon to be released version 2.0 of the core retriever has moved to using dataset
names that include words separated by `-` in line with the datapackage spec. These
names are then converted to `_` for compatibility with some database managment systems.
This resulted in `fetch()` not finding the temporary files it had downloaded because
the dataset name and relevant piece of the file name didn't match precisely. This
converts the dataset name to `_` when matching.
Fixes #75.

Accomodate new retriever naming conventions in fetch

---

R/ecoretriever.R

Get updates was storing the output of running `retriever update`, setting
it's class to `update_log` and returning this output. The current output
from `retriever update` isn't genearlly useful, it's mostly just a progress
bar, and for some reason changing it's class was creating an error (see #82)
so this just change just prints the third value from `update_log`, which
indicates that the update is complete.
Fixes #82.

Don't change the class or return the update log

---

README.md

The package is now posted on CRAN #100 ... hooray! Let's update the download badge and then release a version 1.0.0 on github.

Update download badge

---

.Rbuildignore
LICENSE.md

Implements the solution by @dhimmel and @gavinsimpson for including a proper
license file without upsetting CRAN:
https://github.com/tidyverse/tidyr/pull/267

Specify full license text in repository

---

R/rdataretriever.R

This pull addresses the issues discussed in issue #106.
There are currently inconsistencies in the naming of the data structures returned by `fetch()`. Datasets without hyphens in their name return the indexed data frames’ names without the original dataset name (`data<-fetch(‘portal’)` yields `data$main`) while datasets with hyphens in their name return data frames with the dataset name (`data<-fetch(‘mammal-community-db’)` yields `data$mammal_community_db_species` instead of `data$species`).
The proposed solution by @dmcglinn of deleting line 102 does not solve that issue. That line is important to the renaming structure as it removes the dataset name ‘header’ from non-hyphenated datasets (in the example above, without line 102, there would be `data$portal_main`). The reason it does not …

Issue 106 Fixes

---

.travis.yml
DESCRIPTION
R/rdataretriever.R
README.md
man/get_citation.Rd
tests/testthat.R
tests/testthat/test-retriever.R

Use Travis CI for automated testing. Installs the most recent release of the `retriever` from pypi so that the functions in the R package can then be tested.
Also fixes a documentation related warning to avoid failing based on the warning.

Create basic testing infrastructure

---

R/rdataretriever.R

R and RStudio return differently formatted Windows paths, which causes issues
for checking for retriever installations when it isn't on the path. This normalizes
all paths to use single '/' separaters to allow this to the handled consistently.

Normalize paths on Windows

---

README.md

The name change means we lost download tracking under the old project name. This
lists both download badges.

Include downloads for ecoretriever

---

DESCRIPTION

R now supports ORCIDs for author identification:
https://ropensci.org/technotes/2018/10/08/orcid/
Closes #119.

Add ORCIDs for authors

---

README.md

The current release does not work on Windows because it fails to ever use the correct `r-reticulate` environment.
See https://github.com/weecology/retriever/issues/1390 for the bug report that triggered this realization.

Recommend using devtools to install reticulate

---

DESCRIPTION

Hello from rOpenSci!
The official [rOpenSci docs server](https://docs.ropensci.org) which we [announced](https://ropensci.org/technotes/2019/06/07/ropensci-docs/) in June is fully ready for production now. Our server automatically builds and hosts pkgdown sites for all ropensci packages.
- Official documentation URL: https://docs.ropensci.org/rdataretriever
- Website build logs: https://dev.ropensci.org/job/rdataretriever (click "last build" -> "console output")
If all seems good, we strongly suggest to add the URL to the package DESCRIPTION file and include this in the next CRAN update. This has two major benefits:
- Pkgdown does automatic [cross-linking](https://pkgdown.r-lib.org/dev/articles/linking.html) to other pkgdown sites that can be found via CRAN. This means that if another …

Add official docs URL to description

---

Dockerfile

We were using the MTU mirror, but it is currently down #217 and the cloud mirror should be more stable (and probably faster).

Use Cloud CRAN mirror in Docker-based testing

---

tests/testthat/test-retriever.R

MariaDB was failing to connect using the connection file (#172).
I turned the tests back on in the hopes that this issue had been fixed upstream and everything now passes.
Closes #172.

Reactivate MariaDB tests

---

DESCRIPTION
README.md

Installation is now easier and more stable due to improvements in reticulate.
These changes update the minimum reticulate requirements and simplify
the installation instructions accordingly.
* This removes the need for windows specific install instructions,
closes #196, and closes #199.
* The updates to reticulate also fix #176.
Closes #214.

Update and simplify installation instructions

---

docker-compose.yml
tests/testthat/test-retriever.R

skip_on_cran tests aren't currently running. This manually sets the
appropriate environmental variable to ensure they run.
Also Re-deactivates MySQL/MariaDB tests which only appeared to be
working but acutally weren't running.

Ensure all tests run on Travis

---

R/rdataretriever.R

retriever was updated to use the preffered -dev format instead of .dev.
This format is properly handled by semver::parse_version so we can keep
the dev indication now.

Update retriever version parsing to use -dev

---

R/rdataretriever.R

I think this fixed everything based on:
https://cloud.r-project.org/web/checks/check_results_rdataretriever.html
Fixes #242

Avoid CRAN NOTE from checking retriever version

---

Dockerfile
R/rdataretriever.R

Window's cran test platform fails due to this functionality
To release v3.0, we are removing and providing it as
a function for users to run. This will be replaced later

Disable check_retriever_availability

---

paper/paper.md

This orders the affiliations to line up with the order of names in the author list. Delhi Technological University was removed because it didn't appear to be associated with anyone, but please check to ensure that is correct. Also please give this is careful check to make sure I didn't make any mistakes in the re-ordering since this is important to get precisely right.

Order affiliations by use

---

vignettes/provenance.Rmd

Since the data changes,
the hash value always changes and will error in this example.

Do not evaluate the example
