DESCRIPTION
R/ecoretriever.R
man/get_updates.Rd

After submitting the package to CRAN the I was informed that there was a broken URL, the date was old,  and that I needed to explicitly import two functions from the package utils. These commits fix those problems.

Fix CRAN errors

---

R/ecoretriever.R

These are now supported in the Data Retriever so needed to be added here.
Fixes #77.

Add json and xml as output options

---

DESCRIPTION
R/rdataretriever.R
README.md
man/check_for_retriever.Rd
man/datasets.Rd
man/download.Rd
man/fetch.Rd
man/get_updates.Rd
man/install.Rd
man/print.update_log.Rd
man/reset.Rd
man/run_cli.Rd
man/set_home.Rd

Examples using the new script names
The changes also use the new names that do not have - or _
fixes #89

Change dataset names in source and README.md

---

DESCRIPTION
NEWS.md

I feel like there was also something to do with Rstudio in the updates but I couldn't quickly spot it in the closed PR's. Thanks!

Update news and bump version number

---

DESCRIPTION
README.md

This satisfies the comments we received in #100

Minor changes to URLs for submission of v1.0.0 of package to CRAN.

---

R/rdataretriever.R
man/download.Rd
man/fetch.Rd
man/get_citation.Rd

No code functionality is changed by this commit

Fix broken example in function fetch

---

R/rdataretriever.R

This pull request represents a hack to fix problems with retriever path in Windows systems (see https://github.com/ropensci/rdataretriever/issues/117)

add potential path for retriever in Windows

---

R/rdataretriever.R

I have made changes to the fetch function. It works as follows:
@ethanwhite @henrykironde Please review this PR.

Fetch function update

---

R/rdataretriever.R

Quiet option is removed. Also, before returning bone variable, its length is being checked, if its zero then it implies the dataset was not found and hence it need not be returned. Not sure if anything else has to be changed.
This solves #133 and #113. @ethanwhite @henrykironde Please review this PR.

Quiet option removed

---

.travis.yml

Getting Python and R both working properly on Travis CI is challenging.
These changes address the issue by using conda to install Python.
Also properly creats the postgres database and cleans up some unneeded
lines in .travis.yml.

Fix tests by using conda to install retriever

---

R/rdataretriever.R

Detects the Python and retriever paths
Export the values as PATH and PYTHONHOME

Normalize Path for Checking retriever

---

README.md

Switch to `reticulate` focused installation instructions

---

R/rdataretriever.R

This pull request aims to fix: #180. It adds the functionality to reset a specific dataset similar to as in the python module.

Add functionality to reset a specific dataset

---

DESCRIPTION

Changes of the core infrastructure
Spatial data processing

Bump version to 2.0.0

---

R/rdataretriever.R
tests/testthat/test-retriever.R

add associated test using `portal` as example
I think this should address #207

fix functionality in `get_citation` to return a string as expected

---

R/rdataretriever.R

After actions that influence the offline scripts, automatically update
the list of those scripts.
Fixes #216.

Automatically reload the scripts

---

CODE_OF_CONDUCT.md
DESCRIPTION
README.md

Also replace data retriever domain with direct link to readthedocs

Update all links in docs to https

---

README.md

Recommend remotes for development install

---

paper/paper.md

This will allow the JOSS paper to compile.

Paper fixes.

---

paper/paper.md

Fixing whitespace

---

DESCRIPTION

Cf https://github.com/r-universe/ropensci/actions/runs/1564041333 via https://ropensci.r-universe.dev/ui#builds

Adding missing vignette dependency

---

R/rdataretriever.R

This fixes #293 such that we can pass in CI and on our docs server.

automatically install python module if unavailable

---

R/rdataretriever.R

Use pip install git+https://git@github.com/weecology/retriever.git
instead of the release pip install retriever

Install from main

---

.Rbuildignore
DESCRIPTION

Remove LazyData field
